// import { foo } from "./foo";

import { FOO, foo } from "./foo";
import { ExceptionState as __ExceptionState, Exception as __Exception } from "./types/exception";
// import { JSON } from "json-as"

// function callFoo(): void {
//   foo();
//   console.log("this should never execute!");
// }

// function bar(): void {

// }
// function callCallFoo(): void {
//   callFoo();
//   console.log("this should never execute!");
// }
// try {const newNamefully shutting down...");
//   process.exit(0);
// }

// namespace BAR {
//   export function bar(): void {
//     abort("Aborted from BAR.bar");
//   }
// }
// export function bar(): void {
//   abort("Aborted from bar");
// }
// try {
//   // foo();
//   // FOO.foo();
//   // bar();
//   BAR.bar();
//   console.log("This should not execute");
// } catch (e) {
//   console.log(e.toString());
// }

// function abortingFunction(): void {
//   abort("Aborted from abortingFunction");
// }

// function nestedAbortingFunction(): void {
//   try {
//     abortingFunction();
//   } catch (e) {
//     abort("Aborted from nestedAbortingFunction");
//   }
// }

class Vec3 {

}


// export function main(): void {
  try {
    foo()
  } catch (e) {
    console.log("Caught Error: " + e.toString())
  }
// }

function bar(): void {
  abort("Aborted from bar");
}